apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-configmap
  namespace: wordpress-namespace
  labels:
    app: wordpress
data:
  WORDPRESS_DB_HOST: "mysql.wordpress-namespace:3306"  # MySQL service ka correct hostname aur port
  WORDPRESS_DB_NAME: "wordpress"  # WordPress database name
  WORDPRESS_DB_USER: "wordpress"  # WordPress database user
  WORDPRESS_DB_PASSWORD: "wordpress"  # WordPress database password
  WORDPRESS_TABLE_PREFIX: "wp_"  # WordPress database table prefix
  WORDPRESS_DEBUG: "false"  # Debugging for WordPress, set to "true" for enabling debug mode

