apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config  # Changed name ye name StatefulSet se match hona chaiye 
  namespace: wordpress-namespace
data:
  MYSQL_DATABASE: wordpress
  MYSQL_USER: wordpress

