apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
  namespace: wordpress-namespace
  labels:
    app: wordpress
spec:
  capacity:
    storage: 6Gi  # Matches the PVC request
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce  # Matches the PVC access mode
  persistentVolumeReclaimPolicy: Retain  # Keeps the PV after the PVC is deleted
  storageClassName: manual  # Ensure this matches your cluster's storage class
  hostPath:
    path: /mnt/data/wordpress  # Local directory path for storage
    type: DirectoryOrCreate

