apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret # ye name StatefulSet ke env me match hona chaiye tab jake pod ready hoga name ke sath me or kubctl get all me error nahi hogii
  namespace: wordpress-namespace
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk  # Base64 for "rootpassword"
  MYSQL_PASSWORD: d29yZHByZXNzCg==  # Base64 for "wordpress"
  WORDPRESS_DB_PASSWORD: d29yZHByZXNzCg==  # Base64 for "wordpress" (add this linei)

