apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deploy
  namespace: wordpress-namespace
  labels:
    app: wordpress-deploy
spec:
  replicas: 1  # Increased replicas for high availability
  selector:
    matchLabels:
      app: wordpress-deploy
  template:
    metadata:
      labels:
        app: wordpress-deploy
    spec:
      initContainers:
      - name: init-mysql-check
        image: busybox
        command:
        - sh
        - -c
        - >
          until nc -z mysql-0.mysql-headless 3306; 
          do 
            echo "Waiting for MySQL to be ready...";
            sleep 5;
          done;
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
      containers:
      - name: wordpress
        image: burhan503/burhan503-wordpress:v1.0
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: wordpress-config
              key: WORDPRESS_DB_HOST
        - name: WORDPRESS_DB_USER
          valueFrom:
            configMapKeyRef:
              name: wordpress-config
              key: WORDPRESS_DB_USER
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: WORDPRESS_DB_PASSWORD
        - name: WORDPRESS_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: wordpress-config
              key: WORDPRESS_DB_NAME
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html/wp-content  # Persistent storage for WordPress content
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-pvc  # PVC for persistent storage
