apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  namespace: wordpress-namespace
data:
  WORDPRESS_DB_HOST: mysql-svc:3306
  WORDPRESS_DB_USER: wordpress
  WORDPRESS_DB_NAME: wordpress

