apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  namespace: wordpress-namespace
  labels:
    app: wordpress-deploy
spec:
  selector:
    app: wordpress-deploy  # Matches the labels in the deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080  # Corrected field name
  type: NodePort  # Expose the service externally using NodePort

