apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: wordpress-namespace
  labels:
    app: mysql
type: Opaque
data:
  mysql-root-password: cm9vdHBhc3N3b3Jk        # Base64 encoded password (e.g., "password")
  mysql-user: d29yZHByZXNzCg==                 # Base64 encoded username (e.g., "user")
  mysql-password: d29yZHByZXNzCg==             # Base64 encoded user password (e.g., "password")

