apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: wordpress-namespace
  labels:
    app: mysql
spec:
  selector:
    app: mysql  # Selects pods with the label 'app: mysql'
  ports:
    - protocol: TCP
      port: 3306    # The port exposed by the service
      targetPort: 3306  # The port on the pod where MySQL listens
  clusterIP: None   # Set to None for headless service (useful for StatefulSets)
  type: ClusterIP   # Exposes the service within the cluster

